export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RETURN = 'ORDER_PAY_RETURN'

export const GET_MY_ORDER_REQUEST = 'GET_MY_ORDER_REQUEST'
export const GET_MY_ORDER_SUCCESS = 'GET_MY_ORDER_SUCCESS'
export const GET_MY_ORDER_FAIL = 'GET_MY_ORDER_FAIL'
export const GET_MY_ORDER_RESET = 'GET_MY_ORDER_RESET'

export const GET_ALL_ORDER_REQUEST = 'GET_ALL_ORDER_REQUEST'
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS'
export const GET_ALL_ORDER_FAIL = 'GET_ALL_ORDER_FAIL'
export const GET_ALL_ORDER_RESET = 'GET_ALL_ORDER_RESET'

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'